name: Employee Leave Management CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore API
      run: dotnet restore

    - name: Build API
      run: dotnet build --configuration Release --no-restore

    - name: Publish API
      run: dotnet publish --configuration Release

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install React Dependencies
      run: |
        cd employee-ui
        npm install

    - name: Build React
      run: |
        cd employee-ui
        npm run build